spring:
  application:
    name: discovery-service
  security:
    user:
      name: "test"
      password: "test"

server:
  port: 8000

eureka:
  instance:
    hostname: "localhost"
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka