server:
  port: 8010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        #order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/dev/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/dev
        registration:
          e-shop-dev: #CHANGE
            provider: keycloak
            client-id: devclient  #CHANGE
            client-secret: TnNjrrvWKucbgIpXiHDOeqgRUG5FJC45 #CHANGE
            authorization-grant-type: authorization_code #CHANGE???
            scope: openid
eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8000/eureka
