server:
  port: 8010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
