server:
  port: 8010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        #order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
        #payment
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>.*), /${segment}
        #inventory
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/inventory-service/(?<segment>.*), /${segment}
        #cart
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/cart-service/(?<segment>.*), /${segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/dev/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/dev
        registration:
          e-shop-dev: #CHANGE
            provider: keycloak
            client-id: devclient  #CHANGE
            client-secret: Ccqr6MmWxRvqlYypqogG6PXCXN53MxYU #CHANGE
            authorization-grant-type: authorization_code #CHANGE???
            scope: openid
eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8000/eureka
